#!/usr/bin/env python3
"""Generate deliverables/manifest.md from per-task deliverable files.

Each deliverable is its own file under `deliverables/items/<issue>-<slug>.md` with simple
frontmatter, so parallel tasks never collide on a shared file (the old single-manifest
approach kept causing merge conflicts). Only this script writes `deliverables/manifest.md`
— tasks must not edit it.

Item file format:

    ---
    section: Game (Godot)
    issue: 22
    checked: true
    ---
    Terrain tiles import + demo — non-code artifact — `game/assets/terrain/` (...) (#22)

Usage:
    python3 tools/build_manifest.py             # regenerate deliverables/manifest.md
    python3 tools/build_manifest.py --migrate   # one-time: split an existing manifest.md into items/
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DELIV = ROOT / "deliverables"
ITEMS = DELIV / "items"
MANIFEST = DELIV / "manifest.md"
SECTION_ORDER = ["Foundation / tooling", "Game (Godot)", "Design", "Other"]


def slug(text: str, n: int = 40) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:n].strip("-") or "item"


def parse_item(path: Path):
    text = path.read_text()
    meta, body = {}, text.strip()
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                meta[k.strip()] = v.strip()
        body = m.group(2).strip()
    return meta, body


def _issue_key(meta) -> int:
    try:
        return int(meta.get("issue") or 0)
    except ValueError:
        return 0


def build() -> None:
    sections: dict[str, list] = {}
    if ITEMS.is_dir():
        for p in sorted(ITEMS.glob("*.md")):
            meta, body = parse_item(p)
            sections.setdefault(meta.get("section", "Other"), []).append((meta, body))
    lines = [
        "# Deliverables manifest",
        "",
        "_Generated by `tools/build_manifest.py` from `deliverables/items/*.md` — do not edit"
        " by hand. Tasks add their own item file; run the script to refresh this index._",
        "",
    ]
    key = lambda s: (SECTION_ORDER.index(s) if s in SECTION_ORDER else len(SECTION_ORDER), s)
    for sec in sorted(sections, key=key):
        lines += [f"## {sec}", ""]
        for meta, body in sorted(sections[sec], key=lambda t: _issue_key(t[0])):
            box = "x" if str(meta.get("checked", "true")).lower() == "true" else " "
            lines.append(f"- [{box}] {body}")
        lines.append("")
    MANIFEST.write_text("\n".join(lines).rstrip() + "\n")
    n = sum(len(v) for v in sections.values())
    print(f"wrote {MANIFEST.relative_to(ROOT)} ({n} items across {len(sections)} sections)")


def migrate() -> None:
    if not MANIFEST.exists():
        print("no manifest.md to migrate")
        return
    ITEMS.mkdir(parents=True, exist_ok=True)
    section, seq = "Other", 0
    for line in MANIFEST.read_text().splitlines():
        sm = re.match(r"^##\s+(.*\S)\s*$", line)
        if sm:
            section = sm.group(1).strip()
            continue
        bm = re.match(r"^- \[( |x)\]\s+(.*)$", line)
        if not bm:
            continue
        checked, body = bm.group(1) == "x", bm.group(2).strip()
        im = re.search(r"\(#(\d+)\)", body)
        issue = im.group(1) if im else ""
        seq += 1
        base = issue or f"f{seq:02d}"
        namepart = re.split(r"\s+—\s+", body)[0]
        fn = f"{base}-{slug(namepart)}.md"
        (ITEMS / fn).write_text(
            f"---\nsection: {section}\nissue: {issue}\nchecked: "
            f"{'true' if checked else 'false'}\n---\n{body}\n"
        )
    print(f"migrated existing manifest entries -> {ITEMS.relative_to(ROOT)}/")


if __name__ == "__main__":
    if "--migrate" in sys.argv:
        migrate()
    build()
